name: "Classifier: Trainer"
on:
  schedule:
    - cron: 0 0 5 * *
  repository_dispatch:
    types: [trigger_classifier_trainer]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Install Additional Dependencies
        run: npm install @azure/storage-blob@12
      - name: "Run Classifier: Scraper"
        uses: ./actions/classifier/train/fetch-issues
        with:
          areas: wsl|containers|ssh
          assignees: aeschli|roblourens|chrmarti
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy scipy scikit-learn joblib nltk
      - name: "Run Classifier: Generator"
        run: python ./actions/classifier/train/generate-models/generate.py category
      - name: "Run Classifier: Upload"
        uses: ./actions/classifier/train/upload-models
        with:
          blobContainerName: vscode-remote-release-models
          blobStorageKey: ${{secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING}}